### PR TITLE
Updated some translations

### PR DESCRIPTION
**Pull request by J05HI**
Updated some translations and added the missing german translations.

### CODE REVIEW

**Review by jcgruenhage — COMMENTED** [review]
This change would make sense, if there actually was a translation for this, but this commit doesn't add a translation for it.

**Review by jcgruenhage — APPROVED** [review]
Thanks for all that. I am German myself, just was too lazy so far, to fix that stuff.

**Comment by J05HI** [comment]
Fixed it in the second commit :)  
If you like you can only create the english labels and I'll add the german ones in future updates. 

PS: Keep the good work!!!

**Comment by jcgruenhage** [comment]
I had misread that commit, makes sense now. Thanks :)

**Pull request merged**
