### PR TITLE
Fix wrong confirm button label

### PR DESCRIPTION
**Pull request by J05HI**
Fixed the wrong confirm button label.
"Yes" button was "No" xD

### CODE REVIEW

**Review by jcgruenhage — COMMENTED** [review]
This seems to make sense, from looking at the diff, but I can't actually see problems in the app.. Shouldn't this cause two "no" buttons after the warning?

**Comment by J05HI** [comment]
Yeah it does, this fixes that :)

**Comment by jcgruenhage** [comment]
I just went through the whole intro, without that happening.

**Comment by jcgruenhage** [comment]
Could you provide a screenshot of that happening? I couldn't find it so far.

**Comment by J05HI** [comment]
@jcgruenhage 
You are before this change?

**Comment by J05HI** [comment]
@jcgruenhage 

Before:


After:

**Comment by jcgruenhage** [comment]
Straight from F-Droid:
image

**Comment by J05HI** [comment]
@jcgruenhage 
Strange

**Comment by jcgruenhage** [comment]
Yep. Your commit totally makes sense, and it *should* be broken, if that is actually the code that went into the apk I have on my phone. /me will dig around a bit.

**Comment by J05HI** [comment]
@jcgruenhage 
Okay

**Comment by jcgruenhage** [comment]
Okay, now this makes sense. The extraction of those strings was done after the release of v0.9.6, so currently (on F-Droid/master, not develop), those are hardcoded strings.

**Comment by jcgruenhage** [comment]
Thanks for your contributions :)

**Comment by J05HI** [comment]
Oh okay, thanks!

**Pull request merged**
